theory Chapter3
  imports Chapter2

begin
section\<open>Digression on Groups and Automorphisms\<close>
text \<open>\begin{hartshorne}\defn[group]. A \term{group} is a set $G$ together with a binary operation, called multiplication,
written $ab$ such that
\begin{itemize}
\item[G1] (\term{Associativity}) For all $a,b,c\in G, (ab)c = a(bc)$.
\item[G2] There exists an element $1 \in G$ such that $a \cdot 1 = 1 \cdot a = a \cdot 1 = a$ for all $a$.
\item[G3] For each $a \in G$, there exists an element $a^{-1} \in G$ such that $aa^{-1} = a^{-1}a = 1$.
\end{itemize}\end{hartshorne}
\<close>

text\<open>\begin{hartshorne}
The element 1 is called the \term{identity}, or \term{unit}, element. The element $a^{-1}$ is 
called the \term{inverse} of $a$.
Note that in general the product $ab$ may be different from $ba$. However, we say that the group $G$ is abelian, or commutative, if
\begin{itemize}
\item[G4] For all $a,b\in G,ab=ba$.
\end{itemize}\end{hartshorne}
\<close>

text\<open>\begin{hartshorne}
\label{Examples.} 1. Let $S$ be any set, and let $G$ be the set of \textit{permutations} of the set $S$.
A permutation is a 1–1 mapping of a set S onto S. If $g_1,g_2 \in G$ are two permutations, 
we define $g_1g_2 \in G$ to be the permutation obtained by performing first $g_2$, then $g_1$ (i.e. if $x \in S,(g_1g_2)(x) = g_1(g_2(x))$.)

2. Let $C$ be a configuration, and let $G$ be the set of \textit{automorphisms} of $C$, i.e. 
the set of those permutations of $C$ which send lines into lines. 
Again we define the product $g_1g_2$ of two automorphisms $g_1,g_2$, by performing $g_2$ first, and then $g_1$. 
This group is written Aut$C$.

\defn[homomorphism]. A \term{homomorphism} $\phi : G_1 \xrightarrow{} G_2$ of one group to another 
is a mapping of the set $G_1$ to the set $G_2$ such that
\begin{equation*}
\phi(ab) = \phi(a)\phi(b)
\end{equation*}
for each $a,b \<in> G_1$.
\end{hartshorne}\<close>

text \<open>\begin{hartshorne}
An \term{isomorphism} of one group with another is a homomorphism which is
1–1 and onto.
\end{hartshorne}\<close>

text\<open>\begin{hartshorne}
\defn[subgroup]. Let $G$ be a group. A \term{subgroup} of $G$ is a non-empty subset
$H \subseteq G$, such that for any $a,b \in H, ab \in H$ and $a^{-1} \in H$.
Note that this condition implies $1 \in H$.
\end{hartshorne}\<close>

text\<open>\begin{hartshorne}
\label{Example.} Let $G = \text{Perm}S$, the group of permutatiions of a set $S$, let $x \in S$,
and let $H = \{g \in G\mid g(x) = x\}. Then $H$ is a subgroup of $G$.
\defn[left coset]. Let $G$ be a group, and $H$ a subgroup of $G$. A \term{left coset} of $H$, 
generated by $g \in G$, is 
\begin{equation*}
gH = \{gh \mid h \in H\}
\end{equation*}
\end{hartshorne}\<close>
(* ended before Proposition 3.1 -- to be continued *)

end